# Generated by Django 4.0.4 on 2022-06-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_users_test'),
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugs',
            options={'get_latest_by': 'bug_id', 'ordering': ['-bug_id']},
        ),
        migrations.AddField(
            model_name='bugs',
            name='bug_status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='bugs',
            name='closed_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bugs',
            name='closed_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to='user.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugs',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to='user.users'),
        ),
    ]
