# Generated by Django 4.0.4 on 2022-06-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_alter_bugs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
