# Generated by Django 4.0.4 on 2022-06-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_users_test'),
        ('bug', '0004_alter_bugs_closed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='closed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_by', to='user.users'),
        ),
    ]
