# Generated by Django 4.0.4 on 2022-07-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0009_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='comment',
        ),
    ]
